config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root "books#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
    }
  resources :user_details, only: [:new, :create, :edit, :update]
  resources :profiles, only: [:show]

  namespace :books do
    get "/database", to: "search#database"
  end

  resources :books, only: [:new, :show, :create] do
    resources :orders, only: [:new, :create, :show]
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :ordering, polymorphic: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :set_user, only: [:new, :create]
    before_action :authenticate_user!, only: [:new ,:create]

  def new
    @book = Book.find(params[:book_id])
    @tax = (@book.price + 200) * 0.08
    @total_price = (@book.price + 200) * 1.08
  end

  def create
    @order = @user.orders.create
    @order = @book.orders.create
    @book.update(sold?: "y", o_user_id: @user.id)
  end

  private
  def user_detail_params
    params.require(:user_detail).permit(:lastname, :firstname, :postalcode, :place, :email, :callnumber)
  end

  def user_params
    params.require(:user).permit(:email)
  end

  def set_user
    @user = User.find(current_user)
    @book = Book.find(params[:book_id])
    @user_detail = UserDetail.find_by(user_id: current_user.id)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/create.html.erb
<!-- <!doctype html>
<html lang="en">


<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>techbook</title>
  <meta name="description" content="エンジニアのための書籍シェアリングサービス" />
  <meta name="keywords" content="Ruby, Ruby on Rails, JavaScript, PHP, JAVA, デザイン, 技術書, プログラミング, 書籍" />
  <meta name="author" content="crenoveative">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link href="css/compiled.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Lato:400,400italic,700,700italic,300italic,300' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,300italic,300,600,600italic,700,700italic' rel='stylesheet' type='text/css'>
</head>
<body> -->
  <div class="clear"></div>
  <!-- start Main Wrapper -->
  <div class="main-wrapper">
    <div class="breadcrumb-wrapper bg-light-2">
      <div class="container">
        <ol class="breadcrumb-list booking-step">
          <li><%= link_to "トップ", root_path%></li>
          <li><a href="#">検索結果</a></li>
          <li><a href="#">詳細ページ</a></li>
          <li><a href="#">購入ページ</a></li>
          <li><span>完了画面</span></li>
        </ol>
      </div>
    </div>
    <div class="content-wrapper">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 col-md-9">
            <div class="confirmation-wrapper">
              <div class="payment-success">
                <div class="icon">
                  <i class="pe-7s-check text-success"></i>
                </div>
                <div class="content">
                  <h2 class="heading uppercase mt-0 text-success">購入が完了しました。</h2>
                  <p>ご登録いただいたメール宛にお支払情報に関するご案内を送信させていただきます。</p>
                </div>
              </div>
              <div class="clearfix mb-20">
                <div class="col-xs-8 col-md-4 pl-0">
                  <%= image_tag (@book.content) %>
                </div>
              </div>
              <div class="confirmation-content">
                <div class="section-title text-left">
                  <h4>お届け先詳細</h4>
                </div>
                <ul class="book-sum-list">
                  <li><span class="font600">宛名: </span> <%= @user_detail.lastname %> <%= @user_detail.firstname %> 様</li>
                  <li><span class="font600">書籍名: </span><%= @book.title %></li>
                  <li><span class="font600">お届け先郵便番号: </span><%= @user_detail.postalcode %></li>
                  <li><span class="font600">お届け先住所: </span><%= @user_detail.place %></li>
                  <li><span class="font600">お支払金額合計: </span><%= @book.total_price %>円</li>
                </ul>
              </div>
              <div class="text-right">
              <%= link_to "マイページへ", edit_user_detail_path(current_user), class: "btn btn-primary btn-inverse" %>
              <button > </button>
            </div>
            </div>
          </div>
          <div class="col-sm-4 col-md-3 mt-50-xs">
            <aside class="sidebar with-filter">
              <div class="sidebar-inner">
                <div class="sidebar-module">
                  <h4 class="heading mt-0">お問い合わせ</h4>
                  <div class="sidebar-module-inner">
                    <p class="mb-10">東京都渋谷区道玄坂２丁目新大宗ビル３号館８階</p>
                    <ul class="help-list">
                      <li><span class="font600">電話番号</span>: 090-0000-0000</li>
                      <li><span class="font600">Email</span>: support@tech-book.com</li>
                      <li><span class="font600">Twitter</span>: @tech-book</li>
                    </ul>
                  </div>
                </div>
              </div>
            </aside>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- end Main Wrapper -->

  <footer class="footer">
    <div class="container">
      <div class="main-footer">
        <div class="row">
          <div class="col-xs-12 col-sm-5 col-md-3">
            <div class="footer-logo">
              <img src="images/techbook_logo.png"  alt="Logo" />
            </div>
            <p class="footer-address">150-0000 東京都渋谷区道玄坂２丁目<br>新大宗ビル３号館８階<br/> <i class="fa fa-phone"></i> +66 28 878 5452 <br/> <i class="fa fa-phone"></i> +66 2 547 2223 <br/> <i class="fa fa-envelope-o"></i> <a href="#">support@techbook.com</a></p>
            <div class="footer-social">
              <a href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Github"><i class="fa fa-github"></i></a>
            </div>
            <p class="copy-right">&#169; Copyright 2016 techbook. All Rights Reserved</p>
          </div>
          <div class="col-xs-12 col-sm-7 col-md-9">
            <div class="row gap-10">
              <!-- <div class="col-xs-12 col-sm-4 col-md-3 col-md-offset-3 mt-30-xs"> -->
              <div class="col-xs-12 col-sm-4 col-md-3 mt-30-xs col-md-offset-3">
                <h5 class="footer-title">techbookについて</h5>
                <ul class="footer-menu">
                  <li><a href="#">運営会社について</a></li>
                  <li><a href="#">利用規約</a></li>
                  <li><a href="#">プライバシーポリシー</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
<!-- start Back To Top -->
  <div id="back-to-top">
     <a href="#"><i class="fa fa-angle-up"></i></a>
  </div>
  <!-- end Back To Top -->



  <!-- JS -->
  <script type="text/javascript" src="js/jquery-1.11.3.min.js"></script>
  <script type="text/javascript" src="js/jquery-migrate-1.2.1.min.js"></script>
  <script type="text/javascript" src="bootstrap/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="js/jquery.waypoints.min.js"></script>
  <script type="text/javascript" src="js/jquery.easing.1.3.js"></script>
  <script type="text/javascript" src="js/SmoothScroll.min.js"></script>
  <script type="text/javascript" src="js/jquery.slicknav.min.js"></script>
  <script type="text/javascript" src="js/jquery.placeholder.min.js"></script>
  <script type="text/javascript" src="js/instagram.min.js"></script>
  <script type="text/javascript" src="js/spin.min.js"></script>
  <script type="text/javascript" src="js/jquery.introLoader.min.js"></script>
  <script type="text/javascript" src="js/select2.full.js"></script>
  <script type="text/javascript" src="js/jquery.responsivegrid.js"></script>
  <script type="text/javascript" src="js/ion.rangeSlider.min.js"></script>
  <script type="text/javascript" src="js/readmore.min.js"></script>
  <script type="text/javascript" src="js/slick.min.js"></script>
  <script type="text/javascript" src="js/validator.min.js"></script>
  <script type="text/javascript" src="js/jquery.raty.js"></script> 
  <script type="text/javascript" src="js/customs.js"></script>

<!-- </body>

</html> -->

app/views/orders/new.html.erb
  <div class="clear"></div>
  <!-- start Main Wrapper -->
  <div class="main-wrapper">
    <div class="breadcrumb-wrapper bg-light-2">
      <div class="container">
        <ol class="breadcrumb-list booking-step">
          <li><%= link_to "トップページ", root_path %></li>
          <li><a href="#">検索結果</a></li>
          <li><a href="#">詳細画面</a></li>
          <li><span>お支払い</span></li>
          <li><span>完了</span></li>
        </ol>
      </div>
    </div>
    <div class="content-wrapper">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 visible-xs mb-50">
            <div class="price-summary-wrapper">
              <h4 class="heading mt-0 text-primary uppercase">注文内容</h4>
              <ul class="price-summary-list">
                <li>
                  <h6 class="heading mt-0 mb-0"><%= @book.title %></h6>
                  <p class="font12 text-light"></span> <% @book.category_list.each do |category_tag| %><%= category_tag %>
                  <% end %></p>
                </li>
                <li class="divider"></li>
                <li>
                  <h6 class="heading mt-20 mb-5 text-primary uppercase">価格内訳</h6>
                  <div class="row gap-10 mt-10">
                    <div class="col-xs-7 col-sm-7">
                      本体価格
                    </div>
                    <div class="col-xs-5 col-sm-5 text-right">
                      <%= @book.price %>円
                    </div>
                  </div>
                  <div class="row gap-10 mt-10">
                    <div class="col-xs-7 col-sm-7">
                      送料
                    </div>
                    <div class="col-xs-5 col-sm-5 text-right">
                      200円
                    </div>
                  </div>
                  <div class="row gap-10 mt-10">
                    <div class="col-xs-7 col-sm-7">
                      消費税
                    </div>
                    <div class="col-xs-5 col-sm-5 text-right">
                      <%= @tax.round %>円
                    </div>
                  </div>
                </li>
                <li class="divider"></li>
                <li class="text-right font600 font14">
                  <%= @total_price.round %>円
                </li>
                <li class="divider"></li>
                <li>
                  <div class="row gap-10 font600 font14">
                    <div class="col-xs-9 col-sm-9">
                      購入点数
                    </div>
                    <div class="col-xs-3 col-sm-3 text-right">
                      1
                    </div>
                  </div>
                </li>
                <li class="total-price">
                  <div class="row gap-10">
                    <div class="col-xs-6 col-sm-6">
                      <h5 class="heading mt-0 mb-0 text-white">Amount due</h5>
                      <p class="font12">合計金額</p>
                    </div>
                    <div class="col-xs-6 col-sm-6 text-right">
                      <span class="block font20 font600 mb-5"><%= @total_price.round %>円</span>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-sm-8 col-md-9" role="main">
            <div class="section-title text-left">
              <h3><%= @book.title %><small>を購入します。</small></h3>
            </div>
            <div class="payment-container">
                <div class="payment-box">
                  <div class="payment-header">
                    <div class="number">
                      !
                    </div>
                    <h5 class="heading mt-0">お届け先詳細</h5>
                    <p><spna class="necessary-info">*...必須情報</spna></p>
                  </div>


                   <div class="payment-content">
                   <ul class= "payment-traveller">
                    <li>
                    <strong>*氏名:</strong>
                    <%= @user_detail.lastname%><%= @user_detail.firstname%>
                    </li>
                    <li>
                    <strong>*メールアドレス:</strong>
                    <%= @user.email %>
                    </li>
                    <li>
                    <strong>電話番号:</strong>
                    <%= @user_detail.callnumber%>
                    </li>
                    <li>
                    <strong>*郵便番号:</strong>
                    <%= @user_detail.postalcode%>
                    </li>
                    <li>
                    <strong>*住所</strong>
                    <%= @user_detail.postalcode%>
                    </li>
                  </ul>
                  <button class= "btn btn-primary btn-sm btn-inverse">登録情報の編集</button>
                   </div>
                </div>
            </div>
            <div class="checkbox-block">
              <input id="accept_booking" name="accept_booking" type="checkbox" class="checkbox" value="paymentsCreditCard"/>
              <label class="" for="accept_booking"><a href="#">利用規約</a>及び<a href="#">プライバシーポリシー</a>に同意します。</label>
            </div>
            <div class="row mt-20 clearfix">
              <div class="col-sm-12 col-md-12">
                <%= button_to "注文を確定する", book_orders_path(@book.id), method: :post, html:{ class: "btn btn-primary" }, action: "show" %>
              </div>
            </div>
          </div>
          <div class="col-sm-4 col-md-3 hidden-xs">
            <div class="price-summary-wrapper">
              <h4 class="heading mt-0 text-primary uppercase">注文内容</h4>
              <ul class="price-summary-list">
                <li>
                  <h6 class="heading mt-0 mb-0"></h6>
                  <p class="font12 text-light">デザイン</p>
                </li>
                <li class="divider"></li>
                <li>
                  <h6 class="heading mt-20 mb-5 text-primary uppercase">価格内訳</h6>
                  <div class="row gap-10 mt-10">
                    <div class="col-xs-7 col-sm-7">
                      本体価格
                    </div>
                    <div class="col-xs-5 col-sm-5 text-right">
                      <%= @book.price %>円
                    </div>
                  </div>
                  <div class="row gap-10 mt-10">
                    <div class="col-xs-7 col-sm-7">
                      送料
                    </div>
                    <div class="col-xs-5 col-sm-5 text-right">
                      200円
                    </div>
                  </div>
                  <div class="row gap-10 mt-10">
                    <div class="col-xs-7 col-sm-7">
                      消費税
                    </div>
                    <div class="col-xs-5 col-sm-5 text-right">
                      <%= @tax %>円
                    </div>
                  </div>
                </li>
                <li class="divider"></li>
                <li class="text-right font600 font14">
                  <%= @book_price %>円
                </li>
                <!-- 送料は固定？ -->
                <li class="divider"></li>
                <li>
                  <div class="row gap-10 font600 font14">
                    <div class="col-xs-9 col-sm-9">
                      購入点数
                    </div>
                    <div class="col-xs-3 col-sm-3 text-right">
                      1
                    </div>
                  </div>
                </li>
                <li class="total-price">
                  <div class="row gap-10">
                    <div class="col-xs-6 col-sm-6">
                      <h5 class="heading mt-0 mb-0 text-white">Amount due</h5>
                      <p class="font12">合計金額</p>
                    </div>
                    <div class="col-xs-6 col-sm-6 text-right">
                      <span class="block font20 font600 mb-5"><%= @book_price %>円</span>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- end Main Wrapper -->
  <footer class="footer">
    <div class="container">
      <div class="main-footer">
        <div class="row">
          <div class="col-xs-12 col-sm-5 col-md-3">
            <div class="footer-logo">
              <img src="images/techbook_logo.png" alt="Logo" />
            </div>
            <p class="footer-address">150-0000 東京都渋谷区道玄坂２丁目<br>新大宗ビル３号館８階<br/> <i class="fa fa-phone"></i> +66 28 878 5452 <br/> <i class="fa fa-phone"></i> +66 2 547 2223 <br/> <i class="fa fa-envelope-o"></i> <a href="#">support@techbook.com</a></p>
            <div class="footer-social">
              <a href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Github"><i class="fa fa-github"></i></a>
            </div>
            <p class="copy-right">&#169; Copyright 2016 techbook. All Rights Reserved</p>
          </div>
          <div class="col-xs-12 col-sm-7 col-md-9">
            <div class="row gap-10">
              <!-- <div class="col-xs-12 col-sm-4 col-md-3 col-md-offset-3 mt-30-xs"> -->
              <div class="col-xs-12 col-sm-4 col-md-3 mt-30-xs col-md-offset-3">
                <h5 class="footer-title">techbookについて</h5>
                <ul class="footer-menu">
                  <li><a href="#">運営会社について</a></li>
                  <li><a href="#">利用規約</a></li>
                  <li><a href="#">プライバシーポリシー</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- start Back To Top -->
  <div id="back-to-top">
     <a href="#"><i class="fa fa-angle-up"></i></a>
  </div>
  <!-- end Back To Top -->
<!-- JS -->
<script type="text/javascript" src="js/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="js/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" src="bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="js/jquery.waypoints.min.js"></script>
<script type="text/javascript" src="js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="js/SmoothScroll.min.js"></script>
<script type="text/javascript" src="js/jquery.slicknav.min.js"></script>
<script type="text/javascript" src="js/jquery.placeholder.min.js"></script>
<script type="text/javascript" src="js/instagram.min.js"></script>
<script type="text/javascript" src="js/spin.min.js"></script>
<script type="text/javascript" src="js/jquery.introLoader.min.js"></script>
<script type="text/javascript" src="js/select2.full.js"></script>
<script type="text/javascript" src="js/jquery.responsivegrid.js"></script>
<script type="text/javascript" src="js/ion.rangeSlider.min.js"></script>
<script type="text/javascript" src="js/readmore.min.js"></script>
<script type="text/javascript" src="js/slick.min.js"></script>
<script type="text/javascript" src="js/validator.min.js"></script>
<script type="text/javascript" src="js/jquery.raty.js"></script> 
<script type="text/javascript" src="js/customs.js"></script>

<script>

/**
*  Sidebar Sticky
*/

!function ($) {

  $(function(){

    var $window = $(window)
    var $body   = $(document.body)

    var navHeight = $('.navbar').outerHeight(true) + 50

    $body.scrollspy({
      target: '.scrollspy-sidebar',
      offset: navHeight
    })

    $window.on('load', function () {
      $body.scrollspy('refresh')
    })

    $('.scrollspy-container [href=#]').click(function (e) {
      e.preventDefault()
    })

    // back to top
    setTimeout(function () {
      var $sideBar = $('.scrollspy-sidebar')

      $sideBar.affix({
        offset: {
          top: function () {
            var offsetTop      = $sideBar.offset().top
            var sideBarMargin  = parseInt($sideBar.children(0).css('margin-top'), 10)
            var navOuterHeight = $('.scrollspy-nav').height()

            return (this.top = offsetTop - navOuterHeight - sideBarMargin)
          }
        , bottom: function () {
            return (this.bottom = $('.scrollspy-footer').outerHeight(true))
          }
        }
      })
    }, 100)
  })

}(window.jQuery)

</script>

app/views/orders/show.html.erb
<!-- <!doctype html>
<html lang="en">


<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>techbook</title>
  <meta name="description" content="エンジニアのための書籍シェアリングサービス" />
  <meta name="keywords" content="Ruby, Ruby on Rails, JavaScript, PHP, JAVA, デザイン, 技術書, プログラミング, 書籍" />
  <meta name="author" content="crenoveative">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link href="css/compiled.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Lato:400,400italic,700,700italic,300italic,300' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,300italic,300,600,600italic,700,700italic' rel='stylesheet' type='text/css'>
</head>
<body> -->
  <div class="clear"></div>
  <!-- start Main Wrapper -->
  <div class="main-wrapper">
    <div class="breadcrumb-wrapper bg-light-2">
      <div class="container">
        <ol class="breadcrumb-list booking-step">
          <li><a href="">トップ</a></li>
          <li><a href="#">検索結果</a></li>
          <li><a href="#">詳細ページ</a></li>
          <li><a href="#">購入ページ</a></li>
          <li><span>完了画面</span></li>
        </ol>
      </div>
    </div>
    <div class="content-wrapper">
      <div class="container">
        <div class="row">
          <div class="col-sm-8 col-md-9">
            <div class="confirmation-wrapper">
              <div class="payment-success">
                <div class="icon">
                  <i class="pe-7s-check text-success"></i>
                </div>
                <div class="content">
                  <h2 class="heading uppercase mt-0 text-success">購入が完了しました。</h2>
                  <p>ご登録いただいたメール宛にお支払情報に関するご案内を送信させていただきます。</p>
                </div>
              </div>
              <div class="clearfix mb-20">
                <div class="col-xs-8 col-md-4 pl-0">
                  <img src="images/books/book1.png" alt="">
                </div>
              </div>
              <div class="confirmation-content">
                <div class="section-title text-left">
                  <h4>お届け先詳細</h4>
                </div>
                <ul class="book-sum-list">
                  <li><span class="font600">宛名: </span> せきや じょうじ 様</li>
                  <li><span class="font600">書籍名: </span> ランディングページ・デザインメソッド</li>
                  <li><span class="font600">お届け先郵便番号: </span> 150-0000</li>
                  <li><span class="font600">お届け先住所: </span>東京都渋谷区道玄坂２丁目新大宗ビル３号館８階</li>
                  <li><span class="font600">お支払金額合計: </span>1200円</li>
                </ul>
              </div>
              <div class="text-right">
              <%= link_to "マイページへ", edit_user_detail_path(current_user), class: "btn btn-primary btn-inverse" %>
              <button > </button>
            </div>
            </div>
          </div>
          <div class="col-sm-4 col-md-3 mt-50-xs">
            <aside class="sidebar with-filter">
              <div class="sidebar-inner">
                <div class="sidebar-module">
                  <h4 class="heading mt-0">お問い合わせ</h4>
                  <div class="sidebar-module-inner">
                    <p class="mb-10">東京都渋谷区道玄坂２丁目新大宗ビル３号館８階</p>
                    <ul class="help-list">
                      <li><span class="font600">電話番号</span>: 090-0000-0000</li>
                      <li><span class="font600">Email</span>: support@tech-book.com</li>
                      <li><span class="font600">Twitter</span>: @tech-book</li>
                    </ul>
                  </div>
                </div>
              </div>
            </aside>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- end Main Wrapper -->

  <footer class="footer">
    <div class="container">
      <div class="main-footer">
        <div class="row">
          <div class="col-xs-12 col-sm-5 col-md-3">
            <div class="footer-logo">
              <img src="images/techbook_logo.png"  alt="Logo" />
            </div>
            <p class="footer-address">150-0000 東京都渋谷区道玄坂２丁目<br>新大宗ビル３号館８階<br/> <i class="fa fa-phone"></i> +66 28 878 5452 <br/> <i class="fa fa-phone"></i> +66 2 547 2223 <br/> <i class="fa fa-envelope-o"></i> <a href="#">support@techbook.com</a></p>
            <div class="footer-social">
              <a href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Github"><i class="fa fa-github"></i></a>
            </div>
            <p class="copy-right">&#169; Copyright 2016 techbook. All Rights Reserved</p>
          </div>
          <div class="col-xs-12 col-sm-7 col-md-9">
            <div class="row gap-10">
              <!-- <div class="col-xs-12 col-sm-4 col-md-3 col-md-offset-3 mt-30-xs"> -->
              <div class="col-xs-12 col-sm-4 col-md-3 mt-30-xs col-md-offset-3">
                <h5 class="footer-title">techbookについて</h5>
                <ul class="footer-menu">
                  <li><a href="#">運営会社について</a></li>
                  <li><a href="#">利用規約</a></li>
                  <li><a href="#">プライバシーポリシー</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
<!-- start Back To Top -->
  <div id="back-to-top">
     <a href="#"><i class="fa fa-angle-up"></i></a>
  </div>
  <!-- end Back To Top -->



  <!-- JS -->
  <script type="text/javascript" src="js/jquery-1.11.3.min.js"></script>
  <script type="text/javascript" src="js/jquery-migrate-1.2.1.min.js"></script>
  <script type="text/javascript" src="bootstrap/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="js/jquery.waypoints.min.js"></script>
  <script type="text/javascript" src="js/jquery.easing.1.3.js"></script>
  <script type="text/javascript" src="js/SmoothScroll.min.js"></script>
  <script type="text/javascript" src="js/jquery.slicknav.min.js"></script>
  <script type="text/javascript" src="js/jquery.placeholder.min.js"></script>
  <script type="text/javascript" src="js/instagram.min.js"></script>
  <script type="text/javascript" src="js/spin.min.js"></script>
  <script type="text/javascript" src="js/jquery.introLoader.min.js"></script>
  <script type="text/javascript" src="js/select2.full.js"></script>
  <script type="text/javascript" src="js/jquery.responsivegrid.js"></script>
  <script type="text/javascript" src="js/ion.rangeSlider.min.js"></script>
  <script type="text/javascript" src="js/readmore.min.js"></script>
  <script type="text/javascript" src="js/slick.min.js"></script>
  <script type="text/javascript" src="js/validator.min.js"></script>
  <script type="text/javascript" src="js/jquery.raty.js"></script> 
  <script type="text/javascript" src="js/customs.js"></script>

<!-- </body>

</html> -->