config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root "books#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
    }
  resources :user_details, only: [:new, :create, :edit, :update]
  resources :profiles, only: [:show]

  namespace :books do
    get "/database", to: "search#database"
  end

  resources :books, only: [:new, :show, :create] do
    resources :orders, only: [:new, :create, :show]
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  enum state: {very_good: 0, good: 1, so_so: 2, bad: 3}

  belongs_to :o_user, :class_name => 'User', :foreign_key => 'o_user_id'
  belongs_to :e_user, :class_name => 'User', :foreign_key => 'e_user_id'
  belongs_to :user_detail
  has_many :orders, as: 'ordering'
  has_many :likes

  before_validation :add_js
  validates :title, presence: true
  validates :title, length: { maximum: 60 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  # validates :state, presence: true

  mount_uploader :content, BookImageUploader
  acts_as_taggable_on :categories
  def tax
    (price + 200) * 0.08.round
  end

  def total_price
    (price + 200) * 1.08.round
  end

  scope :costry, -> { where("price > ?", 3000) }
  # Book.costry
  scope :writen_about, -> { where("name like ?", "%#{theme}") }
  # Book.costry.writen_about("Java")
  # =>「高価」で「Java」について書かれた本を探している

  # default_scope -> { order("created_at desc") }
  # => indexで代用

  def add_js
    self.title = self.title.gsub(/js/) do |matched|
    "javascript"
    end
  end

  after_destroy do |book|
    Rails.logger.info "Book is deleted: #{book.attributes.inspect}"
  end
end

app/controllers/books/search_controller.rb
class Books::SearchController < ApplicationController
  before_action :books_search

 def database
    @searcher = { category: params[:category], keyword: params[:keyword] }
    @categories = ActsAsTaggableOn::Tag.all.order(taggings_count: :desc)
  end

  private
  def books_search
    if params[:category].present?
      if params[:keyword].present?
        @books = Book.tagged_with(params[:category]).where("title LIKE %#{params[:keyword]}%", "%#{params[:keyword]}%").includes(:o_user)
      else
        @books = Book.tagged_with(params[:category]).includes(:o_user)
      end
    else
      @books = Book.where("title LIKE ?", "%#{params[:keyword]}").includes(:o_user)
    end
    if params[:sold] == "y"
      @books = @books.where(o_user_id: nil)
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    if user_signed_in?
      @user_detail = UserDetail.find_by(user_id: current_user.id)
      @mastname = @user_detail.try(:lastname) || ''
      @mastname += @user_detail.try(:firstname) || '名無し'
      @mastname += 'さん'
    else
      @mastname  = 'ログイン/新規登録'
    end
    @books = Book.includes(:e_user).page(params[:page]).per(4)
    @categories = ActsAsTaggableOn::Tag.most_used(7)
  end

  def new
    @book = Book.new
  end

  def create
    @book = current_user.e_books.build(book_params)
    if @book.save
      @book.update(sold?: "n")
      redirect_to root_path, notice: 'new book has been exhibited successfully'
    else
      redirect_to new_book_path, alert: 'error'
    end
  end

  def show
    @book = Book.find(params[:id])
    @user_detail = UserDetail.find_by(id: @book.user_detail.id)
    @related_books = Book.tagged_with(@book.category_list, any: true).uniq.where.not(id: @book.id)
    # max 3冊まで
  end

  private

  def book_params
    @user_detail = UserDetail.find_by(user_id: current_user.id)
    params.require(:book).permit(:title, :sub_title, :price, :state, :description, :content, :category_list).merge(e_user_id: current_user.id, user_detail_id: @user_detail.id)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div class="GridLex-col-3_sm-4_xs-12 mb-30">
  <div class="package-grid-item">
      <div class="image">
        <%= link_to image_tag(book.content.url),book_path(book) %>
        <div class="absolute-in-image">
          <% book.category_list.each do |category_tag| %>
            <div class="duration" ><span><%= category_tag %></span></div>
          <% end %>
          <% if book.sold? == "y" %>
            <div class="sold_out_image" >
            <img src= "assets/soldout.png" >
            </div>
          <% end %>
        </div>

      </div>
      <div class="content clearfix">
        <h5><%= book.title %></h5>

        <div class="absolute-in-content">
          <span class="btn"><i class="fa fa-heart-o"></i></span>
          <div class="price">$<%= book.total_price %></div>
        </div>
      </div>
  </div>
</div>

app/views/books/_relatedBook.html.erb
<div class="GridLex-col-4_sm-4_xs-12 mb-20">
  <div class="package-grid-item">
    <div class="image">
      <%= link_to image_tag(book.content.url), book_path(book) %>
      <div class="absolute-in-image">
        <% book.category_list.each do |category_tag| %>
          <div class="duration" ><span><%= category_tag %></span></div>
        <% end %>
      </div>
    </div>
    <div class="content clearfix">
      <h6><%= book.title %></h6>
      <div class="absolute-in-content">
        <div class="price"><%= book.price %></div>
      </div>
    </div>
  </div>
</div>

app/views/books/_searchedBook.html.erb
<div class="col-md-6 col-lg-4 pl-0 ml-0">
  <div class="package-list-item clearfix pl-15">
    <a href="#" class="package-list-item-link">
      <div class="image">
        <%= image_tag book.content %>
        <div class="absolute-in-image">
          </div>
        </div>
      </div>
        <div class="content">
          <div class="row gap-10">
            <div class="col-sm-12 col-md-12">
          <h5><%= book.title %></h5>
            <p class="line18">ランディングページの開発をするフロントエンドのエンジニアには必須の本になります。</p>
            </div>
          <div class="col-sm-12 col-md-12 text-left-sm">
            <div class="price">1000円</div>
            </div>
          </div>
        </div>
    </a>
  </div>
</div>

app/views/books/index.html.erb
  <!-- BEGIN # MODAL LOGIN -->
  <div class="modal fade modal-login modal-border-transparent" id="loginModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <button type="button" class="btn btn-close close" data-dismiss="modal" aria-label="Close">
          <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
        </button>
        <div class="clear"></div>
        <!-- Begin # DIV Form -->
        <div id="modal-login-form-wrapper">
          <!-- Begin # Login Form -->
          <%= render partial:'devise/sessions/login'%>
          <!-- End # Login Form -->
          <!-- Begin | Lost Password Form -->

          <!-- End | Lost Password Form -->
          <!-- Begin | Register Form -->
          <%= render partial: 'devise/registrations/signup'%>
          <!-- End | Register Form -->
        </div>
        <!-- End # DIV Form -->
      </div>
    </div>
  </div>
  <!-- END # MODAL LOGIN -->
  <!-- start Container Wrapper -->
  <div class="container-wrapper">
  <%= render 'layouts/messages' %>
    <!-- start Header -->
    <header id="header">
      <!-- start Navbar (Header) -->
      <nav class="navbar navbar-primary navbar-fixed-top navbar-sticky-function">
        <div class="navbar-top">
          <div class="container">
            <div class="flex-row flex-align-middle">
              <div class="flex-shrink flex-columns">
                <a class="navbar-logo" href="#">
                  <img src="assets/techbook_logo.png" alt="Logo" />
                </a>
              </div>
              <div class="flex-columns">
                <div class="pull-right">
                  <div class="navbar-mini">
                    <ul class="clearfix">
                      <% if user_signed_in? %>
                      <li class="dropdown bt-dropdown-click hidden-xs">
                        <a id="currncy-dropdown" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                          <i class="ion-android-settings hidden-xss"></i> メニュー
                          <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="language-dropdown">
                        <% if @user_detail.present? %>
                          <li><%= link_to "My Page", edit_user_detail_path(current_user) %></li>
                        <% else %>
                          <li><%= link_to "My Page", new_user_detail_path %></li>
                        <% end %>
                          <li><%= link_to "Favorite List" %></li>
                          <li><%= link_to "Exhibits", new_book_path %></li>
                          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                        </ul>
                      </li>
                      <% end %>
                      <li class="user-action">
                        <% if user_signed_in? %>
                          <div class="btn"><%= @mastname %></div>
                        <% else %>
                          <a data-toggle="modal" href="#loginModal" class="btn"><%= @mastname %></a>
                        <% end %>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div id="slicknav-mobile"></div>
      </nav>
      <!-- end Navbar (Header) -->
    </header>


    <div class="clear"></div>
    <!-- start Main Wrapper -->
    <div class="main-wrapper">
      <!-- start hero-header with windows height -->
      <div class="hero" style="background-image:url('assets/books.jpeg');">
        <div class="container">
          <div class="row">
            <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
              <h1 class="hero-title">読んだ技術書は、<br>次の世代のエンジニアへ。</h1>
              <p class="lead">エンジニアのための書籍シェアリングサービス</p>
            </div>
          </div>
          <div class="main-search-wrapper full-width">
            <%= form_tag books_database_path, method: :get do %>
            <div class="inner">
              <div class="column-item">
                <div class="form-group">
                  <%= select "", :category, @categories.pluck(:name), { include_blank: "カテゴリを選択" }, { class: "select select2-multi form-control" } %>
                </div>
              </div>
              <div class="column-item" id="long-column-item">
                <div class="form-group">
                  <%= text_field "", :keyword, name: "month", class: "form-control", placeholder: "キーワード" %>
                </div>
              </div>
              <div class="column-item for-btn">
                <div class="form-group">
                  <%= submit_tag "書籍を検索", class: "btn btn-primary btn-block" %>
                </div>
              </div>
            <% end %>
            </div>
          </div>
        </div>
      </div>
      <section class="bg-light new-books">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
              <div class="section-title">
                <h3>新着の技術書一覧</h3>
                <p>新着で出品された技術書の一覧です。</p>
              </div>
            </div>
          </div>
          <div class="GridLex-gap-30-wrappper package-grid-item-wrapper">
            <div class="GridLex-grid-noGutter-equalHeight">
              <%= render partial: 'books/book', collection: @books %>
            </div>
             <%= paginate(@books) %>
          </div>
        </div>
      </section>
      <section class="overflow-hidden why-us-half-image-wrapper">
        <div class="GridLex-grid-noGutter-equalHeight">
          <div class="GridLex-col-6_sm-12">
            <div class="why-us-half-image-content">
              <div class="section-title text-left">
                <h3>techbookだからできること</h3>
                <p>techbookならではのサービスを紹介します。</p>
              </div>
              <div class="featured-item">
                <h4>中古書籍なのでリーズナブル</h4>
                <div class="content clearfix">
                  <div class="icon">
                    <i class="pe-7s-users"></i>
                  </div>
                  <p>新品で買うと高額な技術書も、techbookで買うことでリーズナブルな価格で入手することができます。</p>
                </div>
              </div>
              <div class="featured-item">
                <h4>簡単クレジットカード決済</h4>
                <div class="content clearfix">
                  <div class="icon">
                    <i class="pe-7s-home"></i>
                  </div>
                  <p>書店に行かなくてもオンラインで簡単に購入していただけます。</p>
                </div>
              </div>
              <div class="featured-item">
                <h4>出品者のレビューが見られるので安心</h4>
                <div class="content clearfix">
                  <div class="icon">
                    <i class="pe-7s-car"></i>
                  </div>
                  <p>出品者のレビューをたくさんある技術書の中で比較するための指標としてお使いいただけます。</p>
                </div>
              </div>
            </div>
          </div>
          <div class="GridLex-col-6_sm-12 image-bg">
            <div class="image-bg" style="background-image:url('assets/books_on_desk2.jpg');"></div>
          </div>
        </div>
      </section>
      <section class="bg-light">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
              <div class="section-title">
                <h3>話題のユーザー</h3>
                <p></p>
              </div>
            </div>
          </div>
          <div class="testimonial-wrapper">
            <div class="row">
              <div class="col-xs-12 col-sm-12 col-md-6">
                <div class="testimonial-item clearfix">
                  <div class="image">
                    <img src="assets/testimonial-01.png" alt="yamane" />
                  </div>
                  <div class="content">
                    <h4>山根祐亮</h4>
                    <h6>Railsエンジニア</h6>
                    <p>RubyやJavaScriptの本を買わせていただきました。自分がまだエンジニアとしての歴が浅くてお金に余裕がなかったころ、いつも人から借りて本を技術書でいたので、今こういったサービスで本を買うことができるエンジニアは幸せだと思います。</p>
                  </div>
                </div>
                <div class="rating-wrapper">
                <div class="raty-wrapper">
                  <div class="star-rating-read-only" data-rating-score="4.0"></div>
                </div>
              </div>

              </div>
              <div class="col-xs-12 col-sm-12 col-md-6">
                <div class="testimonial-item clearfix">
                  <div class="image">
                    <img src="assets/testimonial-02.png" alt="maehira" />
                  </div>
                  <div class="content">
                    <h4>前平亮祐</h4>
                    <h6>デザイナー</h6>
                    <p>デザインの本って新品だととても高いので、助かっています。辞書代わりにつねに手元においておきたい技術書こそ、ハードで買いましょう！</p>
                  </div>
                </div>
                <div class="rating-wrapper">
                <div class="raty-wrapper">
                  <div class="star-rating-read-only" data-rating-score="4.0"></div>
                </div>
              </div>

              </div>
            </div>
          </div>
        </div>
      </section>
      <div class="newsletter-wrapper">
        <div class="container">
          <div class="flex-row flex-align-middle flex-gap-30">
            <div class="flex-column flex-sm-12">
              <div class="newsletter-text clearfix">
                <div class="icon">
                  <i class="pe-7s-mail"></i>
                </div>
                <div class="content">
                  <h3>ニュースレターを受け取る</h3>
                  <p>メールアドレスを登録して、最新の技術書情報などをチェックしましょう。</p>
                </div>
              </div>
            </div>
            <div class="flex-columns flex-sm-12">
              <div class="newsletter-form">
                <form class="">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Emailアドレス">
                    <span class="input-group-btn">
                      <button class="btn btn-primary" type="button">登録 <i class="fa fa-long-arrow-right"></i></button>
                    </span>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="overflow-hidden">
        <div class="instagram-wrapper">
          <div id="instagram" class="instagram"></div>
        </div>
      </div>
    </div>
    <!-- end Main Wrapper -->
    <footer class="footer">
      <div class="container">
        <div class="main-footer">
          <div class="row">
            <div class="col-xs-12 col-sm-5 col-md-3">
              <div class="footer-logo">
                <img src="assets/techbook_logo.png" alt="Logo" />
              </div>
              <p class="footer-address">150-0000 東京都渋谷区道玄坂２丁目<br>新大宗ビル３号館８階<br/> <i class="fa fa-phone"></i> +66 28 878 5452 <br/> <i class="fa fa-phone"></i> +66 2 547 2223 <br/> <i class="fa fa-envelope-o"></i> <a href="#">support@techbook.com</a></p>
              <div class="footer-social">
                <a href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook"></i></a>
                <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter"></i></a>
                <a href="#" data-toggle="tooltip" data-placement="top" title="Github"><i class="fa fa-github"></i></a>
              </div>
              <p class="copy-right">&#169; Copyright 2016 techbook. All Rights Reserved</p>
            </div>
            <div class="col-xs-12 col-sm-7 col-md-9">
              <div class="row gap-10">
                <div class="col-xs-12 col-sm-4 col-md-3 mt-30-xs col-md-offset-3">
                  <h5 class="footer-title">techbookについて</h5>
                  <ul class="footer-menu">
                    <li><a href="#">運営会社について</a></li>
                    <li><a href="#">利用規約</a></li>
                    <li><a href="#">プライバシーポリシー</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </div>  <!-- end Container Wrapper -->
  <!-- start Back To Top -->
  <div id="back-to-top">
     <a href="#"><i class="fa fa-angle-up"></i></a>
  </div>
  <script type="text/javascript" src="assets/jquery-1.11.3.min.js"></script>
  <script type="text/javascript" src="assets/jquery-migrate-1.2.1.min.js"></script>
  <script type="text/javascript" src="assets/js/bootstrap.js"></script>
  <script type="text/javascript" src="assets/jquery.waypoints.min.js"></script>
  <script type="text/javascript" src="assets/jquery.easing.1.3.js"></script>
  <script type="text/javascript" src="assets/SmoothScroll.min.js"></script>
  <script type="text/javascript" src="assets/jquery.slicknav.min.js"></script>
  <script type="text/javascript" src="assets/jquery.placeholder.min.js"></script>
  <script type="text/javascript" src="assets/instagram.min.js"></script>
  <script type="text/javascript" src="assets/spin.min.js"></script>
  <script type="text/javascript" src="assets/jquery.introLoader.min.js"></script>
  <script type="text/javascript" src="assets/select2.full.js"></script>
  <script type="text/javascript" src="assets/jquery.responsivegrid.js"></script>
  <script type="text/javascript" src="assets/ion.rangeSlider.min.js"></script>
  <script type="text/javascript" src="assets/readmore.min.js"></script>
  <script type="text/javascript" src="assets/slick.min.js"></script>
  <script type="text/javascript" src="assets/validator.min.js"></script>
  <script type="text/javascript" src="assets/jquery.raty.js"></script>
  <script type="text/javascript" src="assets/customs.js"></script>

app/views/books/show.html.erb
<div class="clear"></div>
  <!-- start Main Wrapper -->
  <div class="main-wrapper scrollspy-container">
    <!-- start end Page title -->
    <div class="page-title detail-page-title" style="background-image:url(<%= asset_path 'books_on_desk2.jpg'%>);">
      <div class="container">
        <div class="flex-row">
          <div class="flex-column flex-md-8 flex-sm-12">
            <h1 class="hero-title"><%= @book.title %></h1>
            <p class="line18"><%= @book.sub_title %></p>
          </div>
          <div class="flex-column flex-md-4 flex-align-bottom flex-sm-12 mt-20-sm">
            <div class="text-right text-left-sm">
              <%= link_to "購入ページへ", new_book_order_path(book_id: @book.id), class: "anchor btn btn-primary"%>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- end Page title -->
    <div class="breadcrumb-wrapper bg-light-2">
      <div class="container">
        <ol class="breadcrumb-list">
          <li><%= link_to "Home", root_path %></li>
          <li><span><%= @book.title %></span></li>
        </ol>
      </div>
    </div>
    <div class="content-wrapper">
      <div class="container">
        <div class="row">
          <div class="col-sm-3 col-xs-12   mb-50-xs">
            <div class="scrollspy-sidebar sidebar-detail" role="complementary">
              <%= image_tag(@book.content) %>
            </div>
          </div>
          <div class="col-md-9 mt-30-xs" role="main">
            <div class="detail-content-wrapper">
                <div id="section-0" class="detail-content">
                  <div class="section-title text-left">
                    <h4>概要</h4>
                  </div>
                    <h5 class="heading"><%= @book.title %></h5>
                    <h5 class="price mt-0">合計金額: <span><%= @book.total_price %>円</span></h5>
                </div>
                <div id="section-2" class="detail-content">
                  <div class="section-title text-left">
                    <h4>詳細</h4>
                  </div>
                  <div class="detail-item">
                    <div class="row">
                      <div class="col-sm-4 col-sm-3">
                        <ul class="list-info no-icon bb-dotted">
                          <li><span class="font600">出品者: </span><a href="#"><%= @user_detail.lastname %><%= @user_detail.firstname %></a></li>
                          <li><span class="font600">本体価格:</span> <%= @book.price %>円</li>
                          <li><span class="font600">送料:</span> 200円</li>
                          <li><span class="font600">カテゴリ:</span> <% @book.category_list.each do |category_tag| %><%= category_tag %>
                            <% end %>
                          </li>
                          <li><span class="font600">状態: </span> やや傷あり</li>
                        </ul>
                      </div>
                      <div class="col-sm-8 col-md-9">
                        <div class="itinerary-wrapper">
                          <div class="itinerary-item">
                            <h5 class="mb-20">この本について</h5>
                            <div class="intro-item-body">
                              <p><%= @book.description %></p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="text-center pt-10">
                      <%= link_to "購入ページへ", new_book_order_path(book_id: @book.id), class: "btn btn-primary btn-full-width"%>
                      <!-- <a href="#" >購入ページヘ</a> -->
                    </div>
                  </div>
                </div>
                <div class="detail-content">
                  <div class="section-title text-left">
                    <h4>関連する書籍</h4>
                  </div>
                  <div class="GridLex-gap-20-wrappper package-grid-item-wrapper on-page-result-page alt-smaller">
                    <div class="GridLex-grid-noGutter-equalHeight">
                      <%= render partial: 'books/relatedBook', collection: @related_books, as: :book %>

                    </div>
                  </div>
                </div>
                <div class="call-to-action">
                  <a href="#" class="btn btn-primary btn-sm btn-inverse">お問い合わせ</a>
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- end Main Wrapper -->

  <footer class="footer">
    <div class="container">
      <div class="main-footer">
        <div class="row">
          <div class="col-xs-12 col-sm-5 col-md-3">
            <div class="footer-logo">
              <img src="<%= asset_path "techbook_logo.png" %>" alt="Logo" />
            </div>
            <p class="footer-address">150-0000 東京都渋谷区道玄坂２丁目<br>新大宗ビル３号館８階<br/> <i class="fa fa-phone"></i> +66 28 878 5452 <br/> <i class="fa fa-phone"></i> +66 2 547 2223 <br/> <i class="fa fa-envelope-o"></i> <a href="#">support@techbook.com</a></p>
            <div class="footer-social">
              <a href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" data-toggle="tooltip" data-placement="top" title="Github"><i class="fa fa-github"></i></a>
            </div>
            <p class="copy-right">&#169; Copyright 2016 techbook. All Rights Reserved</p>
          </div>
          <div class="col-xs-12 col-sm-7 col-md-9">
            <div class="row gap-10">
              <!-- <div class="col-xs-12 col-sm-4 col-md-3 col-md-offset-3 mt-30-xs"> -->
              <div class="col-xs-12 col-sm-4 col-md-3 mt-30-xs col-md-offset-3">
                <h5 class="footer-title">techbookについて</h5>
                <ul class="footer-menu">
                  <li><a href="#">運営会社について</a></li>
                  <li><a href="#">利用規約</a></li>
                  <li><a href="#">プライバシーポリシー</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- start Back To Top -->
  <div id="back-to-top">
     <a href="#"><i class="fa fa-angle-up"></i></a>
  </div>
  <!-- end Back To Top -->

<!-- JS -->
<script type="text/javascript" src= "#{ asset_path 'jquery-1.11.3.min.js' }"></script>
<script type="text/javascript" src="assets/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" src="assets/bootstrap/bootstrap.min.js"></script>
<script type="text/javascript" src="assets/jquery.waypoints.min.js"></script>
<script type="text/javascript" src="assets/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="assets/SmoothScroll.min.js"></script>
<script type="text/javascript" src="assets/jquery.slicknav.min.js"></script>
<script type="text/javascript" src="assets/jquery.placeholder.min.js"></script>
<script type="text/javascript" src="assets/instagram.min.js"></script>
<script type="text/javascript" src="assets/spin.min.js"></script>
<script type="text/javascript" src="assets/jquery.introLoader.min.js"></script>
<script type="text/javascript" src="assets/select2.full.js"></script>
<script type="text/javascript" src="assets/jquery.responsivegrid.js"></script>
<script type="text/javascript" src="assets/ion.rangeSlider.min.js"></script>
<script type="text/javascript" src="assets/readmore.min.js"></script>
<script type="text/javascript" src="assets/slick.min.js"></script>
<script type="text/javascript" src="assets/validator.min.js"></script>
<script type="text/javascript" src="assets/jquery.raty.js"></script> 
<script type="text/javascript" src="assets/customs.js"></script>

<script>

/**
*  Sidebar Sticky
*/

!function ($) {

  $(function(){

    var $window = $(window)
    var $body   = $(document.body)

    var navHeight = $('.navbar').outerHeight(true) + 50

    $body.scrollspy({
      target: '.scrollspy-sidebar',
      offset: navHeight
    })

    $window.on('load', function () {
      $body.scrollspy('refresh')
    })

    $('.scrollspy-container [href=#]').click(function (e) {
      e.preventDefault()
    })

    // back to top
    setTimeout(function () {
      var $sideBar = $('.scrollspy-sidebar')

      $sideBar.affix({
        offset: {
          top: function () {
            var offsetTop      = $sideBar.offset().top
            var sideBarMargin  = parseInt($sideBar.children(0).css('margin-top'), 10)
            var navOuterHeight = $('.scrollspy-nav').height()

            return (this.top = offsetTop - navOuterHeight - sideBarMargin)
          }
        , bottom: function () {
            return (this.bottom = $('.scrollspy-footer').outerHeight(true))
          }
        }
      })
    }, 100)
    
  })

}(window.jQuery)

</script>